name: "Docker build and publish development"

on:
  push:
    branches:
      - feature/gitutil
      - feature/textbox
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      # Setup docker buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Docker build and push on docker hub the development image
      - name: Build and Push Docker Development Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/docker/Dockerfile.dev
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/ccommits-cli:dev
            